// Per-profession data. Starting values are ILLUSTRATIVE (not market rates), in USD.
module.exports = [
{slug:'graphic-designer',name:'graphic designer',Name:'Graphic designer',net:3500,cost:400,bill:55,
 costs:['Design software subscriptions and font licenses','Stock images and asset licenses for client projects','A computer and a calibrated monitor, replaced every 3–4 years','Cloud storage for heavy files','Accountant and professional liability insurance, where relevant'],
 lost:'Unlimited revisions are the biggest drain: every extra round of changes is time the client does not pay for. Add briefing calls and preparing final files for delivery.',
 tips:['Cap revision rounds in the quote (two is common) and bill extra rounds hourly.','Charge for usage rights separately from the creative work.','A logo and a full brand identity are not the same job: sell packages, not loose hours.'],
 unit:'Logo and identity projects sell best as fixed packages. Social media and recurring materials work better as a monthly retainer.',
 faq:[['Should I bill logo revisions hourly?','Include a fixed number of rounds in the project price and bill additional rounds hourly. It prevents endless revisions.'],['Do I charge for usage rights separately?','It is common to define the scope of use in the contract and charge more for wider use, such as advertising or resale.']]},
{slug:'freelance-developer',name:'freelance developer',Name:'Freelance developer',net:5000,cost:400,bill:60,
 costs:['Hosting, domains and paid developer tools','IDE licenses, project management and private version control','A powerful work computer and a second monitor','Courses and time spent learning to stay current','Accountant and professional liability insurance'],
 lost:'Non-billable time comes from requirements discovery, the weekly client call, post-delivery support and technical debt inherited from other people\'s code.',
 tips:['Always estimate with a buffer for integrations and surprises; software projects tend to overrun.','Define what counts as maintenance and what counts as a new feature before you deliver.','Prefer support retainers to one-off requests: they make your income predictable.'],
 unit:'Fixed-price projects with milestone payments work well. For ongoing work, a monthly retainer with included hours protects both sides.',
 faq:[['Should I charge hourly or per project?','Use the hourly rate to find your minimum and for small requests. On larger projects, a fixed price with milestone payments reduces disputes.'],['How do I charge for support after delivery?','Set a warranty period for bugs, then a monthly retainer or an hours package for everything else.']]},
{slug:'translator',name:'translator',Name:'Translator',net:3000,cost:250,bill:60,
 costs:['Computer-assisted translation tools and translation memories','Dictionaries and specialist terminology databases','Professional association fees and certifications','Computer, monitor and an ergonomic keyboard','Accountant, plus insurance if you handle sensitive documents'],
 lost:'Much of the non-billable time is quote requests that never go ahead, handling awkward file formats and terminology research before you start.',
 tips:['Charge per source word, but set a minimum per job to cover preparation time.','Review your rate when the text is highly technical or has complex formatting.','Rush jobs justify a clear surcharge agreed before you accept.'],
 unit:'The usual unit is a per-word rate. Work out how many words you translate per hour and check that the per-word price covers your minimum hourly rate.',
 faq:[['How do I convert an hourly rate into a per-word rate?','Divide your minimum hourly rate by the number of words you translate in an hour, including review.'],['Should I charge less for repeated text?','You can discount repetitions detected by your tool, but keep a minimum per job.']]},
{slug:'copywriter',name:'copywriter and content writer',Name:'Copywriter and content writer',net:3200,cost:200,bill:55,
 costs:['SEO tools and plagiarism checkers','Grammar, style and note-taking subscriptions','Publication subscriptions for research','A computer and a reliable internet connection','Accountant'],
 lost:'Research, interviews, client-requested revisions and the constant search for new work take far more time than the writing itself.',
 tips:['Price research in: an 800-word article rarely takes only the time it takes to write.','Sell by deliverable (article, sales page) rather than per word when the work is strategic.','Limit revisions and always ask for a written brief.'],
 unit:'Blog posts can be priced per piece, sales pages and emails per project, and regular content as a monthly retainer.',
 faq:[['Should I charge per word or per article?','A per-article or per-project price reflects the research involved. A per-word price suits simple, high-volume orders.'],['How many revisions should I include?','Two rounds are usually reasonable. Put it in writing before you start.']]},
{slug:'photographer',name:'photographer',Name:'Photographer',net:3500,cost:700,bill:40,
 costs:['Wear and replacement of cameras, lenses and lighting','Memory cards, drives and backups','Editing software and online client galleries','Equipment and liability insurance','Travel and parking'],
 lost:'For every hour shooting there are several of culling, editing, delivery and client communication. The billable share tends to be lower than in other professions.',
 tips:['Count editing as working time: it often exceeds the time spent shooting.','Charge for travel and waiting time at events.','Sell packages with a set number of edited photos so clients can compare value.'],
 unit:'Events and portraits sell as packages with hours of coverage and delivered photos. Commercial photography combines a day rate with a usage license.',
 faq:[['Why use a low billable percentage?','Because editing, file management and finding clients take up a large part of your time and are not billed separately.'],['Should I charge for editing separately?','You can include it in the package or bill it hourly for jobs that need heavy retouching.']]},
{slug:'videographer',name:'videographer and video editor',Name:'Videographer and video editor',net:3800,cost:800,bill:45,
 costs:['Cameras, lenses, microphones and lighting, replaced on a plan','Editing and color grading software','Storage: video takes a lot of space and needs backups','Music and sound effect licenses','A powerful computer and long render times'],
 lost:'Rendering, client revisions and script meetings eat hours that never show up on the shoot-day clock.',
 tips:['Price shooting, editing and music licenses separately.','Define the number of versions and export formats included.','Ask for a deposit before you start: the investment in equipment and time is high.'],
 unit:'Video projects sell per finished piece with a defined length. Regular social media content fits a monthly retainer.',
 faq:[['How do I charge for video revisions?','Include one or two rounds in the price and bill further rounds hourly. State it clearly in the quote.'],['Is music paid for separately?','Yes, licenses cost money. Include them in the quote or pass them on to the client transparently.']]},
{slug:'social-media-manager',name:'social media manager',Name:'Social media manager',net:2800,cost:250,bill:55,
 costs:['Scheduling and analytics tools','Design and short-video editing subscriptions','Stock imagery and music for content','A phone and computer for production','Accountant'],
 lost:'Replying to messages, following trends and justifying results to the client are ongoing tasks that rarely appear in the original quote.',
 tips:['Sell retainers with a set number of posts and interactions included.','Define what is out of scope: paid ads, out-of-hours replies, photo production.','Send a simple monthly report: it justifies the retainer and reduces cancellations.'],
 unit:'A monthly retainer is the natural model. Charge for ad management and video production as separate services.',
 faq:[['How do I set a monthly retainer?','Work out the monthly hours needed, multiply by your minimum hourly rate and add a margin for extra requests.'],['Should I include ad management?','It is a distinct service with its own workload. Charge for it separately.']]},
{slug:'virtual-assistant',name:'virtual assistant',Name:'Virtual assistant',net:2200,cost:150,bill:65,
 costs:['Productivity and communication tools','A password manager and task management software','A computer, headset and a good internet connection','Accountant','Training in tools clients ask for'],
 lost:'Switching context between several clients, managing expectations and handling urgent requests cuts into truly productive time.',
 tips:['Sell monthly hour packages with an expiry period.','Bill in 15- or 30-minute increments, with a minimum per request.','Avoid clients who demand instant availability without paying for it.'],
 unit:'Monthly hour banks are the norm. Specialist services (inbox management, scheduling) can have their own price.',
 faq:[['Should I charge hourly or by package?','Monthly hour packages give you predictability; ad-hoc hourly billing suits new clients.'],['Can I charge for urgent requests?','Yes. Set a surcharge for requests outside the agreed hours.']]},
{slug:'tutor',name:'tutor and trainer',Name:'Tutor and trainer',net:2400,cost:150,bill:50,
 costs:['Materials, textbooks and video lesson platforms','A digital whiteboard or tablet','Travel, if you teach at students\' homes','Accountant','Ongoing teaching training'],
 lost:'Preparing lessons, marking work, rescheduling sessions and finding students take many hours a week. Demand is concentrated in certain times of the year.',
 tips:['The lesson is what you bill, but preparation and travel must be reflected in the price.','Set a clear cancellation policy.','Sell monthly lesson packages: they reduce no-shows and give you stability.'],
 unit:'Individual lessons are billed per session. Corporate training can be priced per day or per group.',
 faq:[['Why can\'t I just charge the lesson time?','Because preparation, travel and unfilled slots reduce your real income per hour.'],['How do I handle cancellations?','Set a minimum notice period in writing and charge for the lesson if it is not respected.']]},
{slug:'consultant',name:'independent consultant',Name:'Independent consultant',net:6000,cost:500,bill:50,
 costs:['Travel and accommodation for client visits','Training, certifications and industry events','Management and remote-meeting software','Professional liability insurance','Accountant and legal help with contracts'],
 lost:'Consultative selling is slow: exploratory calls, tailored proposals and relationship building take months before they produce revenue.',
 tips:['Charge for the value you deliver to the client, not just the hours spent.','Avoid long free proposals: limit the initial diagnosis.','Contracts with scope, deadlines and staged payments protect you from constant changes.'],
 unit:'Diagnostics and projects get a fixed price; ongoing support is billed as a retainer or as pre-agreed days of work.',
 faq:[['Can I charge more than my minimum rate?','You should. The minimum is the floor below which you lose money; the selling price should reflect the value to the client.'],['How do I charge for exploratory meetings?','Define a short paid diagnostic instead of endless free meetings.']]}
];
