// Dados por profissão. Valores de partida são ILUSTRATIVOS (não são taxas de mercado).
module.exports = [
{slug:'designer-grafico',name:'designer gráfico',Name:'Designer gráfico',net:1800,cost:300,bill:55,
 costs:['Subscrição de software de design (suites criativas, tipos de letra)','Banco de imagens e licenças de fontes para projetos','Computador e ecrã calibrado, com renovação a cada 3–4 anos','Armazenamento na cloud para ficheiros pesados','Contabilista e seguro de responsabilidade, se aplicável'],
 lost:'Num estúdio, as revisões ilimitadas são o maior sumidouro: cada ronda extra de alterações é tempo que o cliente não paga. Some a isto as reuniões de briefing e a preparação de ficheiros finais.',
 tips:['Limite as rondas de revisão no orçamento (por exemplo, duas) e cobre as extra à hora.','Cobre a cedência de direitos de utilização separadamente do trabalho criativo.','Um logótipo e uma identidade completa não têm o mesmo preço: venda pacotes, não horas soltas.'],
 unit:'Projetos de identidade e logótipos vendem-se por pacote fechado. Manutenção de redes sociais e materiais recorrentes funcionam melhor em avença mensal.',
 faq:[['Devo cobrar a revisão de um logótipo à hora?','Inclua um número fixo de rondas no preço do projeto e cobre as adicionais à hora. Evita revisões sem fim.'],['Cobro os direitos de autor à parte?','É prática comum definir no contrato o âmbito de utilização e cobrar mais por utilizações alargadas, como publicidade ou revenda.']]},
{slug:'programador-freelancer',name:'programador freelancer',Name:'Programador freelancer',net:2500,cost:250,bill:60,
 costs:['Alojamento, domínios e ferramentas de desenvolvimento pagas','Licenças de IDE, gestão de projetos e controlo de versões privado','Computador de trabalho potente e um segundo ecrã','Cursos e tempo de formação para se manter atualizado','Contabilista e seguro de responsabilidade profissional'],
 lost:'O tempo não faturável vem da descoberta de requisitos, da reunião semanal com o cliente, do suporte pós-entrega e da dívida técnica herdada de código de terceiros.',
 tips:['Estime sempre com margem para integrações e imprevistos; projetos de software costumam derrapar.','Defina o que é manutenção e o que é nova funcionalidade antes de entregar.','Prefira avenças de suporte a pedidos pontuais: dão previsibilidade ao seu rendimento.'],
 unit:'Projetos fechados com marcos de pagamento funcionam bem. Para trabalho contínuo, uma avença mensal com horas incluídas protege ambos os lados.',
 faq:[['Cobro à hora ou por projeto?','Use a hora para calcular o seu mínimo e para pedidos pequenos. Em projetos maiores, um preço fechado com marcos de pagamento reduz discussões.'],['Como cobrar o suporte depois da entrega?','Defina um período de garantia para erros e depois uma avença mensal ou um pacote de horas para o resto.']]},
{slug:'tradutor',name:'tradutor',Name:'Tradutor',net:1500,cost:150,bill:60,
 costs:['Ferramentas de tradução assistida e memórias de tradução','Dicionários e bases terminológicas especializadas','Associação profissional e certificações','Computador, ecrã e teclado ergonómico','Contabilista e seguro, se trabalha com documentos sensíveis'],
 lost:'Muito do tempo não faturável são pedidos de orçamento que não avançam, a gestão de ficheiros em formatos difíceis e a pesquisa terminológica antes de começar.',
 tips:['Cobre por palavra de origem, mas defina um mínimo por trabalho para cobrir o tempo de preparação.','Reveja o seu preço quando o texto é muito técnico ou tem formatação complexa.','Urgências justificam um acréscimo claro e acordado antes de aceitar.'],
 unit:'A unidade habitual é o preço por palavra. Calcule quantas palavras consegue traduzir por hora e confirme que o valor por palavra cobre o seu preço mínimo à hora.',
 faq:[['Como converter preço por hora em preço por palavra?','Divida o seu preço mínimo à hora pelo número de palavras que traduz numa hora, incluindo revisão.'],['Cobro menos por textos repetidos?','Pode aplicar descontos a repetições detetadas pela ferramenta, mas mantenha o mínimo por trabalho.']]},
{slug:'redator',name:'redator e copywriter',Name:'Redator e copywriter',net:1600,cost:120,bill:55,
 costs:['Ferramentas de SEO e verificação de plágio','Subscrições de gramática, estilo e organização de notas','Assinaturas de publicações para pesquisa','Computador e ligação à internet fiável','Contabilista'],
 lost:'Pesquisa, entrevistas, revisões pedidas pelo cliente e a angariação constante de trabalho consomem muito mais tempo do que a escrita em si.',
 tips:['Inclua a pesquisa no preço: um texto de 800 palavras raramente demora só o tempo de escrever.','Venda por resultado (artigo, página de vendas) e não por palavra, quando o trabalho é estratégico.','Limite as revisões e peça sempre um briefing escrito.'],
 unit:'Artigos de blogue podem ter preço por peça; páginas de vendas e emails, por projeto; conteúdo regular, por avença mensal.',
 faq:[['Cobro por palavra ou por artigo?','O preço por artigo ou projeto reflete melhor a pesquisa envolvida. O preço por palavra serve para encomendas simples e de volume.'],['Quantas revisões devo incluir?','Duas rondas costumam ser razoáveis. Defina-o por escrito antes de começar.']]},
{slug:'fotografo',name:'fotógrafo',Name:'Fotógrafo',net:1700,cost:400,bill:40,
 costs:['Desgaste e renovação de câmaras, objetivas e iluminação','Cartões de memória, discos e cópias de segurança','Software de edição e galerias online para clientes','Seguro de equipamento e de responsabilidade civil','Deslocações e estacionamento'],
 lost:'Para cada hora a fotografar há várias de seleção, edição, entrega e comunicação com o cliente. A taxa de horas faturáveis tende a ser mais baixa do que noutras profissões.',
 tips:['Conte a edição como tempo de trabalho: costuma exceder o tempo de fotografia.','Cobre deslocações e tempo de espera em eventos.','Venda pacotes com número de fotografias editadas, para o cliente comparar valor.'],
 unit:'Eventos e retratos vendem-se por pacote com horas de cobertura e fotografias entregues. Fotografia comercial combina um valor de dia com licença de utilização.',
 faq:[['Porque devo usar uma percentagem faturável baixa?','Porque a edição, a gestão de ficheiros e a angariação de clientes ocupam grande parte do tempo e não são faturadas em separado.'],['Cobro a edição à parte?','Pode incluí-la no pacote ou cobrá-la à hora em trabalhos que exigem retoque pesado.']]},
{slug:'videografo',name:'videógrafo e editor de vídeo',Name:'Videógrafo e editor de vídeo',net:1900,cost:450,bill:45,
 costs:['Câmaras, lentes, microfones e iluminação, com renovação planeada','Software de edição e correção de cor','Armazenamento: o vídeo ocupa muito espaço e exige cópias de segurança','Licenças de música e efeitos','Computador potente e renderizações demoradas'],
 lost:'As renderizações, as revisões do cliente e as reuniões de guião consomem horas que não aparecem no cronómetro das filmagens.',
 tips:['Separe o preço de filmagem, edição e licenças de música.','Defina o número de versões e formatos de exportação incluídos.','Peça um sinal antes de começar: o investimento em equipamento e tempo é elevado.'],
 unit:'Projetos de vídeo vendem-se por peça final com duração definida. Conteúdo regular para redes sociais encaixa numa avença mensal.',
 faq:[['Como cobrar as revisões de um vídeo?','Inclua uma ou duas rondas no preço e cobre as seguintes à hora. Deixe-o claro no orçamento.'],['A música paga-se à parte?','Sim, as licenças têm custo. Inclua-as no orçamento ou repasse-as ao cliente de forma transparente.']]},
{slug:'gestor-redes-sociais',name:'gestor de redes sociais',Name:'Gestor de redes sociais',net:1400,cost:140,bill:55,
 costs:['Ferramentas de agendamento e análise','Subscrições de design e edição de vídeo curto','Banco de imagens e música para conteúdos','Telemóvel e computador para produção','Contabilista'],
 lost:'Responder a mensagens, acompanhar tendências e justificar resultados ao cliente são tarefas contínuas que raramente aparecem no orçamento inicial.',
 tips:['Venda avenças com número de publicações e de interações incluídas.','Defina que tarefas ficam fora: anúncios pagos, respostas fora de horas, produção de fotografia.','Entregue um relatório mensal simples: justifica a avença e reduz cancelamentos.'],
 unit:'A avença mensal é o modelo natural. Cobre a gestão de anúncios e a produção de vídeo como serviços separados.',
 faq:[['Como definir uma avença mensal?','Calcule as horas mensais necessárias, multiplique pelo seu preço mínimo à hora e acrescente uma margem para pedidos extra.'],['Incluo a gestão de anúncios?','É um serviço distinto, com carga de trabalho própria. Cobre-o em separado.']]},
{slug:'assistente-virtual',name:'assistente virtual',Name:'Assistente virtual',net:1100,cost:90,bill:65,
 costs:['Ferramentas de produtividade e comunicação','Gestor de passwords e software de gestão de tarefas','Computador, headset e boa ligação à internet','Contabilista','Formação em ferramentas pedidas por clientes'],
 lost:'Mudar de contexto entre vários clientes, gerir expectativas e responder a pedidos urgentes reduz o tempo realmente produtivo.',
 tips:['Venda pacotes de horas mensais com prazo de utilização.','Fature em frações de 15 ou 30 minutos, com um mínimo por pedido.','Evite clientes que exigem disponibilidade imediata sem pagarem por isso.'],
 unit:'Bolsas de horas mensais são a norma. Serviços especializados (gestão de caixa de correio, agenda) podem ter preço próprio.',
 faq:[['Cobro por hora ou por pacote?','Pacotes de horas mensais dão-lhe previsibilidade; a hora avulsa serve para clientes novos.'],['Posso cobrar urgências?','Sim. Defina um acréscimo para pedidos fora do horário combinado.']]},
{slug:'explicador',name:'explicador e formador',Name:'Explicador e formador',net:1200,cost:80,bill:50,
 costs:['Materiais, manuais e plataformas de videoaulas','Quadro digital ou tablet','Deslocações, se dá aulas ao domicílio','Contabilista','Formação pedagógica contínua'],
 lost:'Preparar aulas, corrigir trabalhos, remarcar sessões e angariar alunos ocupam muitas horas por semana. Os picos de procura concentram-se em certas épocas do ano.',
 tips:['Cobre a aula, e a preparação e deslocação devem estar refletidas no preço.','Estabeleça uma política de cancelamento clara.','Venda pacotes mensais de aulas: reduz faltas e dá estabilidade.'],
 unit:'Aulas individuais cobram-se por sessão. Formação para empresas pode ter preço por dia ou por turma.',
 faq:[['Porque não posso cobrar só o valor da aula?','Porque a preparação, as deslocações e as vagas por preencher reduzem o rendimento real por hora.'],['Como lidar com cancelamentos?','Defina por escrito um prazo mínimo de aviso e cobre a aula se não for respeitado.']]},
{slug:'consultor',name:'consultor independente',Name:'Consultor independente',net:3000,cost:300,bill:50,
 costs:['Deslocações e alojamento em visitas a clientes','Formação, certificações e eventos do setor','Software de gestão e de reuniões remotas','Seguro de responsabilidade profissional','Contabilista e apoio jurídico para contratos'],
 lost:'A venda consultiva é longa: reuniões exploratórias, propostas à medida e o desenvolvimento de relações demoram meses antes de gerarem faturação.',
 tips:['Cobre o valor que entrega ao cliente, não apenas as horas gastas.','Evite propostas gratuitas extensas: limite o diagnóstico inicial.','Contratos com âmbito, prazos e pagamentos por fases protegem-no de alterações constantes.'],
 unit:'Diagnósticos e projetos têm preço fechado; acompanhamento contínuo faz-se por avença ou por dias de trabalho previamente acordados.',
 faq:[['Posso cobrar mais do que a minha taxa mínima?','Deve. O valor mínimo é o limite abaixo do qual perde dinheiro; o preço de venda deve refletir o valor para o cliente.'],['Como cobrar reuniões exploratórias?','Defina um diagnóstico pago e curto, em vez de reuniões gratuitas sem fim.']]}
];
