// Free guide content. Worked example (USD): 4000 net/month, 500 costs/month, 30% tax, 60% billable, 40 h/week, 6 weeks off.
module.exports = {
title: '7 mistakes that make freelancers charge less than they should',
intro: 'Many freelancers set their price from the salary they used to earn, from what they saw competitors charge, or from a hunch. The result is long hours and not much left over. Here are the seven most common mistakes and how to fix each one.',
example: 'The example used throughout this guide: you want $4,000 net per month, have $500 of monthly business costs, pay 30% tax on profit, work 40 hours a week, bill 60% of that time and take 6 weeks off a year.',
errors: [
['Dividing your desired salary by 160 hours',
 'A month has about 160 working hours, and 4,000 ÷ 160 gives $25 an hour. It sounds reasonable, but it ignores almost everything: tax, costs and the time you are not billing.',
 'With the full calculation, the same goal needs about $68 an hour. The simple method undercharges by more than half.',
 'Work out the annual revenue you need, then divide it by the hours you can actually bill, not the hours you work.'],
['Forgetting taxes and business costs',
 'The income you want is what is left for you. Taxes apply to your profit, and business costs come out before you earn anything.',
 'In the example, $500 of monthly costs is $6,000 a year that your prices must cover, and 30% tax raises the revenue you need considerably.',
 'Start from your desired net, add costs and adjust for tax: revenue = costs + net ÷ (1 − tax rate). Confirm the rate with your accountant.'],
['Counting every hour as billable',
 'Proposals, unpaid meetings, admin, invoicing, learning and prospecting are all work, but you cannot bill for them. In an eight-hour day, it is rare to bill all eight.',
 'In the example only 60% of hours are billable, which is 24 hours a week, not 40.',
 'Measure for a month: log your time as billable or non-billable. Use the real figure, not the one you wish for.'],
['Ignoring vacations, holidays and sick days',
 'A year has 52 weeks, but a freelancer does not bill in all of them. There is no paid leave or sick pay from your clients.',
 'With 6 weeks off you work 46 weeks: about 1,104 billable hours a year instead of 1,248 if you counted all 52.',
 'Decide how many weeks you will stop and remove them from the calculation before you divide.'],
['Quoting without a risk buffer',
 'Estimates tend to come in short: change requests, slow communication and technical surprises. On a fixed price, the risk is yours.',
 'A 20% buffer on top of your estimate is a common starting point for projects with uncertain requirements.',
 'Cap revision rounds in the contract, define what is out of scope and bill extra changes hourly.'],
['Copying competitors\' prices',
 'You do not know their costs, their taxes or their non-billable time. Their price may be low because they are just starting, or because they never did the math.',
 'If you copy a price below your own minimum, every project moves you closer to a loss.',
 'Work out your minimum first. Then compare: competitors tell you what the market accepts, not what your business needs.'],
['Never reviewing your price',
 'Costs rise and your skills grow, but your price stays the same. Many freelancers charge the same rate for years.',
 'Even a small annual increase covers inflation and the growth in the quality of your work.',
 'Put an annual price review in your calendar. Apply the new rate to new clients and give existing ones advance notice.']
],
checklist: ['I defined the monthly net income I want.','I added up all my business costs as a monthly figure.','I confirmed my tax percentage with an accountant.','I measured my billable hours for a month.','I subtracted weeks for vacation, holidays and sick days.','I added a risk buffer to fixed-price quotes.','I worked out my minimum rate before looking at competitors.','I scheduled an annual price review.'],
close: 'Run the numbers with the free calculator at paxeko530.github.io/preco-hora and keep this guide for your next price review. Figures are illustrative and this guide is not tax or financial advice.'
};
